[package]
name = "deskbot"
version = "0.1.0"
edition = "2021"
authors = ["Nolan J Tait <nolanjtait@gmail.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
autopilot = { version = "0.4.0" }
image = { version = "0.22.4" }
