module Deskbot
  VERSION: String

  class Screen
    def listen: () { (Event) -> untyped } -> untyped
  end

  class Event
    attr_reader type: Symbol
    attr_reader key: Symbol?
    attr_reader button: Integer?
    attr_reader x: Integer?
    attr_reader y: Integer?

    def initialize: (type: Symbol, ?key: Symbol?, ?button: Integer?, ?x: Integer?, ?y: Integer?) -> void

    def self.build: (Hash[String, untyped]) -> Event

    def coords: () -> (Array[Integer] | nil)
    def key_event?: () -> bool
    def mouse_event?: () -> bool
    def move?: () -> bool
    def to_h: () -> Hash[Symbol, untyped]
  end
end
